### ISSUE TITLE
Device server crashes on Windows when reading attribute in between its two devices

### ISSUE THREAD

**Issue by reszelaz** [tango-controls-migration-tests/TangoTickets#19] opened 2018-05-31 15:22 UTC
Not sure if this is PyTango or Tango issue.

We discovered (thanks to @dschick and @rhomspuron!) that on Windows the following scenario causes the device server process to crash.

A device server has two devices of two classes: A and B. The A class defines one attribute: attr. The B class defines one command: cmd. The cmd starts a thread which tries to read attr via a DeviceProxy.

This python [device server](https://github.com/tango-controls/TangoTickets/files/2058798/ds.py.txt) can be used to reproduce it.

We are using:
* Windows 7
* Python(x,y)-2.7.10.0 - can be downloaded from [here](http://ftp.ntua.gr/pub/devel/pythonxy/Python(x,y)-2.7.10.0.exe)
* PyTango-9.2.1 - can be downloaded from [here](https://pypi.python.org/packages/fe/6e/8780412c9b04ba49177032b792e35c0461c1da49b3e204badf817bba23ec/pytango-9.2.1.Win32-py2.7.msi#md5=668c63b09c058225ad377a2ab75f43ee)

**Comment by bourtemb** [comment] 2018-11-15 17:02
Hi,
Thanks for the bug report.
Did you try on Linux?
Is this happening only on Windows?

**Comment by reszelaz** [comment] 2018-11-15 17:36
If I remember correctly this was failing only on Windows. Thanks for looking into this!

**Comment by tiagocoutinho** [comment] 2019-07-19 15:38
Cannot reproduce the problem using:

```
PyTango 9.3.1 (9, 3, 1, 'dev', 1)
PyTango compiled with:
    Python : 3.6.8
    Numpy  : 0.0.0
    Tango  : 9.3.3
    Boost  : 1.70.0

PyTango runtime is:
    Python : 3.6.8
    Numpy  : 1.16.4
    Tango  : 9.3.3
    Boost  : 0.0.0

PyTango running on:
uname_result(system='Windows', node='MSEDGEWIN10', release='10', version='10.0.16299', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
```

I think we can close the issue. Thanks for the help

**Closed as completed by tiagocoutinho** 2019-07-19 15:38 UTC
Labels: bug, Windows
