### ISSUE TITLE
Event subscriptions lost when number of DeviceProxy > 1

### ISSUE THREAD

**Issue by stufisher** [tango-controls-migration-tests/TangoTickets#34] opened 2020-05-18 08:14 UTC
I am having issues using pytango to subscribe to multiple devices, i initially thought this was to do with using the gevented DeviceProxy, but actually it also occurs in the threaded case. Reading through the tickets my issue sounds a lot like https://github.com/tango-controls/TangoTickets/issues/22 but i am running tango 9.3.2 so i think it should be fixed.

I'm running a conda env with the following packages:
```
# conda list | grep tango
lima-camera-simulator-tango 1.9.0                         0    http://bcu-ci.esrf.fr/stable
lima-tango-server         1.9.3                         0    http://bcu-ci.esrf.fr/stable
omniorb                   4.2.2            py37h6bb024c_0    tango-controls
pytango                   9.3.1            py37ha8d69ae_1    tango-controls
tango                     9.3.2                h6bb024c_0    tango-controls
```
and bliss provides the tango dummy server
https://gitlab.esrf.fr/bliss/bliss/-/blob/master/tests/dummy_tg_server.py

On my local dev i'm using the dummy_tg and lima_simulator server, but this happens on the beamline too with different device servers so not convinced they are responsible?

Heres my test code:
```python
import gevent.monkey
gevent.monkey.patch_all(thread=False)

import time
import tango
from tango.gevent import DeviceProxy
import gevent

import logging
logging.basicConfig(level=logging.DEBUG)

logger = logging.getLogger(__name__)


class TangoWrapper:
    def __init__(self, tango_url, props):
        self._tango_url = tango_url
        self._props = props

        self._subscriptions = {}
        self._object = DeviceProxy(self._tango_url)
        self._online = False

        gevent.spawn(self.try_device)

    def try_device(self):
        while True:
            while not self._online:
                try:
                    logger.info(f"Trying to connect to {self._tango_url}")
                    self._object.ping()
                    self._online = True
                    self.subscribe_device()
                except Exception as e:
                    logger.exception(
                        f"Could not connect to {self._tango_url}. Retrying in 10s"
                    )

                time.sleep(10)

            time.sleep(10)

    def subscribe_device(self):
        for p in self._props:
            try:
                self._object.poll_attribute(p, 500)
                self._subscriptions[p] = self._object.subscribe_event(
                    p,
                    tango.EventType.CHANGE_EVENT,
                    self.push_event,
                    # green_mode=tango.GreenMode.Gevent, # do i need this?
                )
            except Exception as e:
                logger.exception(f"Could not subscribe to property {p}")

    def push_event(self, event):
        if not self._online:
            return

        if event.attr_value is not None:
            logger.info(f"Device: {self._tango_url} Attr: {event.attr_value.name} Value: {event.attr_value.value}")

        elif event.errors and self._online:
            error = event.errors[0]
            logger.error(f"Error in push_event for {event.attr_name}: {error.desc}")
            self._online = False


if __name__ == "__main__":
    devices = [
        {
            "tango_url": "localhost:20000/id00/limaccds/simulator1",
            "props": ["acq_status"],
        },
        {"tango_url": "localhost:20000/id00/tango/dummy", "props": ["state"]},
    ]

    objs = []
    for device in devices:
        objs.append(TangoWrapper(device["tango_url"], device["props"]))

    while True:
        time.sleep(10)
        print("sleeping")
```

If i subscribe to a single device no problems, the script returns:
```
# python daiquiri/tango_test.py 
INFO:__main__:Trying to connect to localhost:20000/id00/limaccds/simulator1
INFO:__main__:Device: localhost:20000/id00/limaccds/simulator1 Attr: acq_status Value: Running
sleeping
sleeping
...
```

However as soon as i subscribe to the two devices i end up in a loop of:
```
# python daiquiri/tango_test.py 
INFO:__main__:Trying to connect to localhost:20000/id00/limaccds/simulator1
INFO:__main__:Trying to connect to localhost:20000/id00/tango/dummy
INFO:__main__:Device: localhost:20000/id00/tango/dummy Attr: State Value: CLOSE
INFO:__main__:Device: localhost:20000/id00/limaccds/simulator1 Attr: acq_status Value: Running
sleeping
ERROR:__main__:Error in push_event for tango://localhost:20000/id00/tango/dummy/state: Event channel is not responding anymore, maybe the server or event system is down
ERROR:__main__:Error in push_event for tango://localhost:20000/id00/limaccds/simulator1/acq_status: Event channel is not responding anymore, maybe the server or event system is down
sleeping
INFO:__main__:Trying to connect to localhost:20000/id00/tango/dummy
INFO:__main__:Trying to connect to localhost:20000/id00/limaccds/simulator1
INFO:__main__:Device: localhost:20000/id00/tango/dummy Attr: State Value: CLOSE
INFO:__main__:Device: localhost:20000/id00/limaccds/simulator1 Attr: acq_status Value: Running
ERROR:__main__:Error in push_event for tango://localhost:20000/id00/tango/dummy/state: Event channel is not responding anymore, maybe the server or event system is down
ERROR:__main__:Error in push_event for tango://localhost:20000/id00/limaccds/simulator1/acq_status: Event channel is not responding anymore, maybe the server or event system is down
sleeping
```

Any idea what i am doing wrong here?

**Comment by stufisher** [comment] 2020-05-19 15:42
I've done some more digging into this. It is something to do with creating the objects at the same time and them each launching a greenlet (or thread) to then subscribe to the device attributes. If i add a small delay in the TangoWrapper.__init__ method, say time.sleep(0.1) things play nice. 

Am i spamming the network or something by subscribing to lots of properties essentially simultaneously?

**Comment by andygotz** [comment] 2020-05-19 15:55
There shouldn't be a limit to how many attributes you can subscribe to simultaneously except that it will take some time. What you describe sounds more like a race condition. The current implementation for subscribing triggers a synchronous call to the attribute. This will slow you down. We are thinking of proposing a batched event subscription in the future.

I wonder if other PyTango experts like @ajoubertza or @tiagocoutinho have encountered a similar issue ?

**Comment by tiagocoutinho** [comment] 2020-05-20 08:29
Hi @stufisher,
Thanks for the detailed report.

Indeed looks like a bug.
I am able to reproduce the problem with:
```
PyTango 9.2.5 (9, 2, 5)
PyTango compiled with:
    Python : 3.7.0
    Numpy  : 1.11.3
    Tango  : 9.2.5
    Boost  : 1.67.0

PyTango runtime is:
    Python : 3.7.7
    Numpy  : 1.18.1
    Tango  : 9.2.5
    Boost  : 0.0.0
```

The fact that you use gevent should not make a difference because PyTango uses an internal gevent  thread pool because we cannot access the CORBA socket and make it gevent friendly.

I tried with a threaded version and confirm it also happens.

It looks to me like a recurrent bug we had in the past. After 10s the internal tango event system polls to update its state and for some reason (corruption of its internal state) thinks there is an error and tries to register again. That is why you see an error message followed by an event message.

I say this is coming from the C++ layer. But I request the help for @bourtemb to confirm.

**Comment by stufisher** [comment] 2020-05-20 08:46
Hi @tiagocoutinho, thanks for looking into this. 

Interesting i thought maybe it was something to do with the subscriptions happening concurrently (in their own threads / greenlets), the small sleep i add serialises the subscriptions to some extent, and then the error goes away.

**Comment by bourtemb** [comment] 2020-05-22 07:49
Hi,
This might be linked to the following issue:
https://github.com/tango-controls/cppTango/issues/686

In your case, you are not subscribing from the callback but you are subscribing concurrently from threads different than the main thread so it probably leads to the same result.

I encourage you to try with cppTango 9.3.4-rc5 where https://github.com/tango-controls/cppTango/issues/686 should be fixed.

**Comment by ajoubertza** [comment] 2020-05-23 20:37
> The fact that you use gevent should not make a difference because PyTango uses an internal gevent thread pool because we cannot access the CORBA socket and make it gevent friendly.
> 
> I tried with a threaded version and confirm it also happens.

Could it be this issue https://github.com/tango-controls/pytango/issues/307?  The solution for that was adding the [EnsureOmniThread](https://github.com/tango-controls/pytango/pull/327) context handler and advising its use in custom threads (from PyTango 9.3.2).  In the doc update for that I mentioned that `ThreadPoolExecutor` would be problem.  I don't see an easy way to use this context handler with the gevent thread pool.  We could try this:  

```python
    def try_device(self):
        with tango.EnsureOmniThread():
            while True:
                ...
```
It might work, but I'm not sure what will happen if the same thread from the thread pool is used to handle multiple spawned tasks.  Each of those tasks will instantiate the context handler, and I don't know if it will create a new dummy omnithread ID, or keep the old ID.  If it keeps the old one, that should be fine.  The ID is used to determine ownership for the read/write locks in cppTango, so it must stay fixed for the lifetime of the thread.  @bourtemb may have a better idea about doing `new omni_thread::ensure_self` multiple times in the same thread?

**Comment by bourtemb** [comment] 2020-05-25 00:46
@ajoubertza , I tried again the [C++ example](https://github.com/tango-controls/pytango/files/3879504/test_dev_sub.cpp.tar.gz) provided by @tiagocoutinho on https://github.com/tango-controls/pytango/issues/307, without the ensure_self workaround and I noticed the events are correctly received when using cppTango 9.3.4-rc5 version.
A git bisect session confirmed that PR https://github.com/tango-controls/cppTango/pull/699 solved the issue reported by @tiagocoutinho in the C++ example he provided in https://github.com/tango-controls/pytango/issues/307.
So, I really encourage to try using cppTango 9.3.4-rc5.

**Comment by ajoubertza** [comment] 2020-05-25 09:35
@bourtemb Thanks.  So is there still a use case for `EnsureOmniThread` in PyTango after cppTango 9.3.4-rc5?

**Comment by bourtemb** [comment] 2020-05-26 11:32
> @bourtemb Thanks. So is there still a use case for `EnsureOmniThread` in PyTango after cppTango 9.3.4-rc5?

Sorry. I cannot give you an answer right now. I don't know for the moment.

**Comment by bourtemb** [comment] 2020-05-28 12:47
@stufisher , did you get the chance to test using cppTango 9.3.4-rc5?

**Comment by stufisher** [comment] 2020-06-02 11:49
Hi @bourtemb, thanks for your help and work. I am working in a docker with conda, i dont see a package for this release yet, do you usually make rc packages or wait for full version release? Both the beamline (bliss) and my test envs are using conda, so not straight forward to test without a package.

**Comment by bourtemb** [comment] 2020-06-02 12:01
There are new smaller conda packages in preparation.
There is one for cppTango (9.3.4-rc5 available):
https://anaconda.org/tango-controls/cpptango

This is quite new and there might still be some problems with some dependencies depending on the version of python you're using but you might give it a try...
PyTango 9.3.2 conda package is not yet ready (https://github.com/tango-controls/pytango-conda-recipes/pull/1)

**Comment by ajoubertza** [comment] 2020-07-08 18:51
@stufisher There are now Conda packages available on the tango-control channel.  Latest cppTango is 9.3.4rc6, and pytango 9.3.2.

**Comment by stufisher** [comment] 2020-07-08 19:24
thanks @ajoubertza, ill try and get this tested out on a beamline!

**Closed as completed** 2022-04-06 16:05 UTC
